# Generated by Django 5.2.7 on 2025-10-04 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categorias de Itens',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatusItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Status de Itens',
            },
        ),
        migrations.CreateModel(
            name='TipoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_item', models.CharField(max_length=50, verbose_name='Nº do Item / Etiqueta')),
                ('modelo', models.CharField(max_length=100)),
                ('data_compra', models.DateField(verbose_name='Data da Compra')),
                ('local_compra', models.CharField(blank=True, max_length=150, verbose_name='Local da Compra / Loja')),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Pago (R$)')),
                ('pago_por', models.CharField(blank=True, max_length=100, verbose_name='Pago Por')),
                ('telefone_usuario', models.CharField(blank=True, max_length=20, verbose_name='Telefone do Usuário (Contato)')),
                ('posse_status', models.CharField(choices=[('EM_USO', 'Em Uso'), ('VENDER', 'Para Vender'), ('LIVRE', 'Livre (Em Estoque)')], default='LIVRE', max_length=10, verbose_name='Posse Atual')),
                ('categoria_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipamentos.categoriaitem', verbose_name='Categoria do Item')),
                ('posse_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Em posse do Usuário')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipamentos.marca')),
                ('status_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipamentos.statusitem', verbose_name='Status do Item')),
                ('tipo_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipamentos.tipoitem', verbose_name='Tipo do Item')),
            ],
        ),
    ]
