services:
  # --- 1. Seu Banco de Dados PostgreSQL ---
  - type: postgres
    name: rcostasystem-db
    databaseName: rcostasystem
    user: rcostasystem_user
    plan: free

  # --- 2. Seu Serviço Redis (para o Celery) ---
  - type: redis
    name: redis-rca
    plan: free

  # --- 3. Seu Serviço Web (Aplicação Django) ---
  - type: web
    name: rcostasystem-web
    runtime: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --no-input && python manage.py migrate"
    startCommand: "gunicorn aureon_core.wsgi"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: rcostasystem-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis-rca
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.12.9
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
        
      # --- VARIÁVEIS NÃO SENSÍVEIS ---
      - key: SHAREPOINT_TENANT_ID
        value: "d89ff279-659f-4c3a-b303-1b4eef30a657"
      - key: SHAREPOINT_CLIENT_ID
        value: "b9caaa20-a5cc-4bc8-b192-963624f02f8d"
      - key: SHAREPOINT_DRIVE_ID
        value: "b!SpwqPYYqjUCWVQ7gr3aA5QacSx-59HlKmy8oDyuJDypbVbhLsXahTrV1jtilUkLm"
      - key: SHAREPOINT_SITE_URL
        value: "rcostaadvcombr.sharepoint.com"
      - key: SHAREPOINT_DOC_LIBRARY
        value: "Documentos"
        
      # --- VARIÁVEL SECRETA (NÃO SINCRONIZADA) ---
      - key: SHAREPOINT_CLIENT_SECRET
        sync: false # Diz ao Render: "Eu vou configurar esta manualmente na interface."

  # --- 4. Seu Worker do Celery ---
  - type: worker
    name: celery-worker
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "celery -A aureon_core worker --loglevel=info"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: rcostasystem-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis-rca
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.12.9
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: False
        
      # --- COPIE E COLE AS MESMAS VARIÁVEIS AQUI ---
      - key: SHAREPOINT_TENANT_ID
        value: "d89ff279-659f-4c3a-b303-1b4eef30a657"
      - key: SHAREPOINT_CLIENT_ID
        value: "b9caaa20-a5cc-4bc8-b192-963624f02f8d"
      - key: SHAREPOINT_DRIVE_ID
        value: "b!SpwqPYYqjUCWVQ7gr3aA5QacSx-59HlKmy8oDyuJDypbVbhLsXahTrV1jtilUkLm"
      - key: SHAREPOINT_SITE_URL
        value: "rcostaadvcombr.sharepoint.com"
      - key: SHAREPOINT_DOC_LIBRARY
        value: "Documentos"
        
      # --- VARIÁVEL SECRETA (NÃO SINCRONIZADA) ---
      - key: SHAREPOINT_CLIENT_SECRET
        sync: false
