# Generated by Django 5.2.7 on 2025-10-05 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoGlobal',
            fields=[
                ('singleton_id', models.IntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('habilitar_login_microsoft', models.BooleanField(default=False, help_text='Se ativado, a opção de login via Microsoft será exibida na tela de login.', verbose_name='Habilitar login com a Microsoft')),
                ('habilitar_robo_modulos', models.BooleanField(default=False, help_text='Se ativado, o menu lateral será construído dinamicamente com base nas permissões do usuário.', verbose_name='Habilitar robô de módulos visíveis')),
            ],
            options={
                'verbose_name_plural': 'Configurações Globais',
            },
        ),
    ]
