# Generated by Django 5.2.7 on 2025-10-04 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(help_text="Identificador único para o sistema (ex: 'novo-caso-criado').", unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinatarios', models.TextField()),
                ('assunto', models.CharField(max_length=255)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('enviado_com_sucesso', models.BooleanField(default=False)),
                ('evento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='notificacoes.evento')),
            ],
            options={
                'ordering': ['-data_envio'],
            },
        ),
        migrations.CreateModel(
            name='TemplateEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(max_length=255)),
                ('corpo', models.TextField(help_text='Corpo do e-mail. Pode usar variáveis do Django Template.')),
                ('destinatarios_fixos', models.TextField(blank=True, help_text='E-mails separados por vírgula.')),
                ('ativo', models.BooleanField(default=True)),
                ('enviar_para_grupos', models.ManyToManyField(blank=True, to='auth.group')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='notificacoes.evento')),
            ],
        ),
    ]
