# Generated by Django 5.2.7 on 2025-10-01 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apelido', models.CharField(help_text='Ex: E-mail Principal do Sistema', max_length=100)),
                ('email_host', models.CharField(max_length=100, verbose_name='Servidor SMTP (Ex: smtp.office365.com)')),
                ('email_port', models.PositiveIntegerField(default=587, verbose_name='Porta')),
                ('email_host_user', models.EmailField(max_length=254, verbose_name='Usuário (e-mail de envio)')),
                ('email_host_password', models.CharField(max_length=100, verbose_name='Senha (ou Senha de App)')),
                ('email_use_tls', models.BooleanField(default=True, verbose_name='Usar TLS')),
                ('ativo', models.BooleanField(default=True, help_text='Apenas UMA configuração pode estar ativa.')),
            ],
            options={
                'verbose_name': 'Configuração de Servidor de E-mail',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Evento')),
                ('slug', models.SlugField(help_text="Identificador único para usar no código (será preenchido automaticamente). Ex: 'novo_caso_criado'", unique=True)),
                ('descricao', models.TextField(blank=True, help_text='Descreva o que este evento significa e quais variáveis de contexto estão disponíveis (ex: {{ caso }}, {{ usuario_acao }}).')),
            ],
        ),
        migrations.CreateModel(
            name='TemplateEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_template', models.CharField(help_text="Nome interno para identificar este template, ex: 'E-mail de boas-vindas para cliente'", max_length=150)),
                ('assunto', models.CharField(help_text='Pode usar variáveis como {{ caso.titulo_caso }}', max_length=200)),
                ('corpo', models.TextField(help_text='Pode usar variáveis como {{ caso.cliente.nome_razao_social }} e {{ usuario_acao.get_full_name }}.', verbose_name='Corpo do E-mail')),
                ('destinatarios_fixos', models.TextField(blank=True, help_text='E-mails fixos, separados por vírgula. Ex: email1@exemplo.com', verbose_name='Enviar Cópia Para (E-mails Fixos)')),
                ('ativo', models.BooleanField(default=True, help_text='Se desmarcado, este template não será usado.')),
                ('enviar_para_grupos', models.ManyToManyField(blank=True, help_text='Envia para todos os usuários nestes grupos.', to='auth.group', verbose_name='Enviar para Grupos de Usuários')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='notificacoes.evento')),
            ],
            options={
                'verbose_name': 'Template de E-mail',
                'verbose_name_plural': 'Templates de E-mail',
            },
        ),
    ]
