# Generated by Django 5.2.7 on 2025-10-02 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('notificacoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinatarios', models.TextField()),
                ('assunto', models.CharField(max_length=255)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('enviado_com_sucesso', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-data_envio'],
            },
        ),
        migrations.DeleteModel(
            name='ConfiguracaoEmail',
        ),
        migrations.AlterModelOptions(
            name='templateemail',
            options={},
        ),
        migrations.RemoveField(
            model_name='templateemail',
            name='nome_template',
        ),
        migrations.AddField(
            model_name='evento',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='slug',
            field=models.SlugField(help_text="Identificador único para o sistema (ex: 'novo-caso-criado').", unique=True),
        ),
        migrations.AlterField(
            model_name='templateemail',
            name='assunto',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='templateemail',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='templateemail',
            name='corpo',
            field=models.TextField(help_text='Corpo do e-mail. Pode usar variáveis do Django Template.'),
        ),
        migrations.AlterField(
            model_name='templateemail',
            name='destinatarios_fixos',
            field=models.TextField(blank=True, help_text='E-mails separados por vírgula.'),
        ),
        migrations.AlterField(
            model_name='templateemail',
            name='enviar_para_grupos',
            field=models.ManyToManyField(blank=True, to='auth.group'),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='evento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='notificacoes.evento'),
        ),
    ]
