# Generated by Django 5.2.7 on 2025-10-03 10:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('notificacoes', '0002_notificacao_delete_configuracaoemail_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_label', models.CharField(max_length=100, unique=True, verbose_name='Nome de Exibição do Campo')),
                ('nome_tecnico', models.SlugField(help_text='Nome interno do campo (automático)', max_length=100, unique=True)),
                ('tipo_campo', models.CharField(choices=[('text', 'Texto Curto (CharField)'), ('textarea', 'Texto Longo (TextField)'), ('number', 'Número Decimal (DecimalField)'), ('integer', 'Número Inteiro (IntegerField)'), ('date', 'Data (DateField)'), ('url', 'Link (URLField)'), ('select', 'Lista (Seleção)')], default='text', max_length=20)),
            ],
            options={
                'verbose_name': 'Campo Customizado',
                'verbose_name_plural': 'Campos Customizados',
                'ordering': ['nome_label'],
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do modelo para identificação interna.', max_length=100, unique=True)),
                ('assunto', models.CharField(help_text='Assunto do e-mail. Pode usar variáveis como {{ caso.titulo_caso }}.', max_length=255)),
                ('corpo', models.TextField(help_text='Corpo do e-mail em HTML. Use variáveis como {{ caso.cliente.nome_razao_social }} ou {{ user.get_full_name }}.')),
            ],
            options={
                'verbose_name': 'Modelo de E-mail',
                'verbose_name_plural': 'Modelos de E-mail',
            },
        ),
        migrations.CreateModel(
            name='EstruturaPasta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_pasta', models.CharField(max_length=100, verbose_name='Nome da Subpasta')),
            ],
            options={
                'verbose_name': 'Estrutura de Pasta',
                'verbose_name_plural': 'Estruturas de Pasta',
            },
        ),
        migrations.CreateModel(
            name='EtapaFluxo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('sla_dias', models.PositiveIntegerField(default=0, help_text='Prazo ideal em dias para esta etapa. 0 para sem SLA.', verbose_name='SLA (dias)')),
            ],
            options={
                'verbose_name': 'Etapa do Fluxo',
                'verbose_name_plural': '2. Etapas dos Fluxos',
                'ordering': ['fluxo_trabalho', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Status',
            },
        ),
        migrations.CreateModel(
            name='Advogado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário do Sistema')),
            ],
        ),
        migrations.CreateModel(
            name='Caso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada_rca', models.DateField(verbose_name='Data de Entrada')),
                ('data_entrada_fase', models.DateTimeField(blank=True, null=True, verbose_name='Data de Entrada na Fase Atual')),
                ('data_encerramento', models.DateField(blank=True, null=True, verbose_name='Data de Encerramento')),
                ('titulo_caso', models.CharField(blank=True, max_length=512, verbose_name='Título do Caso')),
                ('sharepoint_folder_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID da Pasta no SharePoint')),
                ('sharepoint_folder_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL da Pasta no SharePoint')),
                ('advogado_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casos', to='casos.advogado', verbose_name='Advogado Responsável')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='AndamentoCaso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_andamento', models.DateField(default=django.utils.timezone.now, verbose_name='Data do Andamento')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('usuario_criacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='andamentos_caso', to='casos.caso')),
            ],
            options={
                'verbose_name': 'Andamento do Caso',
                'verbose_name_plural': 'Andamentos do Caso',
                'ordering': ['-data_andamento'],
            },
        ),
        migrations.CreateModel(
            name='EmailCaso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('microsoft_message_id', models.CharField(help_text='ID único do e-mail na Microsoft Graph.', max_length=255, unique=True)),
                ('de', models.CharField(max_length=255, verbose_name='De')),
                ('para', models.TextField(verbose_name='Para')),
                ('assunto', models.CharField(max_length=255, verbose_name='Assunto')),
                ('preview', models.CharField(max_length=255, verbose_name='Pré-visualização do corpo')),
                ('corpo_html', models.TextField(verbose_name='Corpo do E-mail')),
                ('data_envio', models.DateTimeField(verbose_name='Data de Envio/Recebimento')),
                ('is_sent', models.BooleanField(default=False, help_text='True se foi enviado do sistema, False se foi recebido.')),
                ('thread_id', models.CharField(blank=True, help_text='ID da thread de conversação.', max_length=255, null=True)),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='casos.caso')),
            ],
            options={
                'verbose_name': 'E-mail do Caso',
                'verbose_name_plural': 'E-mails dos Casos',
                'ordering': ['-data_envio'],
            },
        ),
        migrations.CreateModel(
            name='AcaoEtapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título da Ação/Tarefa')),
                ('instrucoes', models.TextField(blank=True, verbose_name='Instruções Padrão')),
                ('etapa_fluxo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acoes', to='casos.etapafluxo')),
            ],
            options={
                'verbose_name': 'Ação da Etapa',
                'verbose_name_plural': '3. Ações das Etapas',
            },
        ),
        migrations.CreateModel(
            name='FluxoInterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_fluxo', models.DateField(verbose_name='Data')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fluxo_interno', to='casos.caso')),
                ('usuario_criacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Fluxo Interno',
                'verbose_name_plural': 'Fluxo Interno',
                'ordering': ['-data_fluxo', '-data_cadastro'],
            },
        ),
        migrations.CreateModel(
            name='FluxoTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Fluxo de Trabalho',
                'verbose_name_plural': '1. Fluxos de Trabalho',
            },
        ),
        migrations.AddField(
            model_name='etapafluxo',
            name='fluxo_trabalho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='casos.fluxotrabalho'),
        ),
        migrations.CreateModel(
            name='GraphWebhookSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_id', models.CharField(max_length=255, unique=True)),
                ('expiration_datetime', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OpcaoCampo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=255)),
                ('nome_label', models.CharField(max_length=100, unique=True, verbose_name='Nome de Exibição do Campo')),
                ('nome_tecnico', models.SlugField(help_text="Nome interno do campo (automático), ex: 'valor_causa'", max_length=100, unique=True)),
                ('campo', models.ForeignKey(limit_choices_to={'tipo_campo': 'select'}, on_delete=django.db.models.deletion.CASCADE, related_name='opcoes', to='casos.campo')),
            ],
            options={
                'verbose_name': 'Campo Customizado',
                'verbose_name_plural': 'Campos Customizados',
                'ordering': ['nome_label'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Produto / Objeto do Serviço')),
                ('estrutura_pastas', models.ManyToManyField(blank=True, to='casos.estruturapasta', verbose_name='Estrutura de Pastas no SharePoint')),
            ],
        ),
        migrations.AddField(
            model_name='fluxotrabalho',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casos.produto'),
        ),
        migrations.AddField(
            model_name='caso',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='casos.produto'),
        ),
        migrations.CreateModel(
            name='OpcaoDecisao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_do_botao', models.CharField(max_length=100, verbose_name='Texto do Botão de Decisão')),
                ('avancar_proxima_etapa', models.BooleanField(default=False, verbose_name='Avançar para Próxima Etapa?')),
                ('aguardar_dias', models.PositiveIntegerField(default=0, help_text='Cria uma tarefa de lembrete para o futuro. 0 para desativado.', verbose_name='Aguardar (dias)')),
                ('enviar_email', models.BooleanField(default=False, verbose_name='Enviar E-mail Automático?')),
                ('acao_etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opcoes_decisao', to='casos.acaoetapa')),
                ('criar_nova_acao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='casos.acaoetapa', verbose_name='Criar Nova Ação/Tarefa')),
                ('modelo_email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notificacoes.templateemail', verbose_name='Usar Modelo de E-mail')),
                ('mudar_etapa_para', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='casos.etapafluxo', verbose_name='Mover para a Etapa Específica')),
                ('atualizar_status_caso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='casos.status', verbose_name='Atualizar Status do Caso para')),
            ],
            options={
                'verbose_name': 'Opção de Decisão',
                'verbose_name_plural': '4. Opções de Decisão',
            },
        ),
        migrations.AddField(
            model_name='caso',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='casos.status'),
        ),
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_execucao', models.DateField(verbose_name='Data de Execução')),
                ('tempo', models.DurationField(verbose_name='Tempo Gasto (HH:MM)')),
                ('descricao', models.TextField(verbose_name='Descrição da Atividade')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to='casos.caso')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Profissional')),
            ],
            options={
                'ordering': ['-data_execucao'],
            },
        ),
        migrations.CreateModel(
            name='UserSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text="Nome da assinatura (ex: 'Padrão', 'Simplificada').", max_length=100)),
                ('corpo_html', models.TextField(verbose_name='Assinatura em HTML')),
                ('is_default', models.BooleanField(default=False, verbose_name='É a assinatura padrão?')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assinatura de Usuário',
                'verbose_name_plural': 'Assinaturas de Usuários',
            },
        ),
        migrations.AlterUniqueTogether(
            name='etapafluxo',
            unique_together={('fluxo_trabalho', 'ordem')},
        ),
        migrations.AlterUniqueTogether(
            name='fluxotrabalho',
            unique_together={('cliente', 'produto')},
        ),
        migrations.CreateModel(
            name='RegraCampo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formato_titulo', models.TextField(blank=True, help_text='Defina o formato do título. Use {{ nome_do_campo }} para as variáveis. Ex: Aviso: {{ aviso }} - Segurado: {{ segurado }} - Tomador: {{ tomador }}', verbose_name='Formato do Título do Caso')),
                ('campos', models.ManyToManyField(to='casos.campo', verbose_name='Campos Customizados para esta Regra')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casos.produto')),
            ],
            options={
                'verbose_name': 'Regra de Campos Customizados',
                'verbose_name_plural': 'Regras de Campos Customizados',
                'unique_together': {('cliente', 'produto')},
            },
        ),
        migrations.CreateModel(
            name='ValorCampoCaso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.TextField(blank=True, null=True)),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casos.campo')),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores_dinamicos', to='casos.caso')),
            ],
            options={
                'verbose_name': 'Valor de Campo Customizado',
                'verbose_name_plural': 'Valores de Campos Customizados',
                'ordering': ['campo__nome_label'],
                'unique_together': {('caso', 'campo')},
            },
        ),
    ]
