# Generated by Django 5.2.7 on 2025-10-05 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcordoCaso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_acordo', models.DateField(verbose_name='Data do Acordo')),
                ('quantidade_parcelas', models.PositiveIntegerField(default=1, verbose_name='Quantidade de Parcelas')),
                ('valor_parcela', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da Parcela')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição do Acordo')),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acordos', to='casos.caso')),
            ],
            options={
                'verbose_name': 'Acordo do Caso',
                'verbose_name_plural': 'Acordos dos Casos',
                'ordering': ['-data_acordo'],
            },
        ),
        migrations.CreateModel(
            name='DespesaCaso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_despesa', models.DateField(verbose_name='Data da Despesa')),
                ('descricao', models.CharField(max_length=500, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesas', to='casos.caso')),
            ],
            options={
                'verbose_name': 'Despesa do Caso',
                'verbose_name_plural': 'Despesas dos Casos',
                'ordering': ['-data_despesa'],
            },
        ),
        migrations.CreateModel(
            name='ParcelaAcordo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_parcela', models.PositiveIntegerField(verbose_name='Nº da Parcela')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('situacao', models.CharField(choices=[('aberto', 'Em Aberto'), ('quitado', 'Quitada')], default='aberto', max_length=10, verbose_name='Situação')),
                ('acordo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='casos.acordocaso')),
            ],
            options={
                'verbose_name': 'Parcela do Acordo',
                'verbose_name_plural': 'Parcelas dos Acordos',
                'ordering': ['data_vencimento'],
            },
        ),
    ]
