# Generated by Django 5.2.7 on 2025-10-04 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opcaocampo',
            options={'verbose_name': 'Opção de Campo de Lista', 'verbose_name_plural': 'Opções de Campos de Lista'},
        ),
        migrations.AlterUniqueTogether(
            name='opcaocampo',
            unique_together={('campo', 'valor')},
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='tempo',
        ),
        migrations.AddField(
            model_name='acaoetapa',
            name='prazo_dias',
            field=models.PositiveIntegerField(default=0, help_text='Número de dias para concluir a tarefa após sua criação. 0 para sem prazo.', verbose_name='Prazo (em dias)'),
        ),
        migrations.AddField(
            model_name='acaoetapa',
            name='responsavel_fixo',
            field=models.ForeignKey(blank=True, help_text="Usado apenas se o tipo acima for 'Usuário Fixo'.", null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário Fixo'),
        ),
        migrations.AddField(
            model_name='acaoetapa',
            name='tipo_prazo',
            field=models.CharField(choices=[('corridos', 'Dias Corridos'), ('uteis', 'Dias Úteis')], default='uteis', max_length=10, verbose_name='Tipo de Prazo'),
        ),
        migrations.AddField(
            model_name='acaoetapa',
            name='tipo_responsavel',
            field=models.CharField(choices=[('CRIADOR_ACAO', 'Usuário que Concluiu a Ação Anterior'), ('RESPONSAVEL_CASO', 'Responsável Pelo Caso'), ('USUARIO_FIXO', 'Usuário Fixo (especificar abaixo)')], default='CRIADOR_ACAO', max_length=20, verbose_name='Atribuir Responsável Para'),
        ),
        migrations.AddField(
            model_name='caso',
            name='etapa_atual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casos_nesta_etapa', to='casos.etapafluxo'),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='minutos_gastos',
            field=models.PositiveIntegerField(default=0, verbose_name='Tempo Gasto (em minutos)'),
        ),
        migrations.AlterField(
            model_name='caso',
            name='advogado_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casos_responsavel', to='casos.advogado', verbose_name='Advogado Responsável'),
        ),
        migrations.CreateModel(
            name='HistoricoEtapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateTimeField(auto_now_add=True)),
                ('data_saida', models.DateTimeField(blank=True, null=True)),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_etapas', to='casos.caso')),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='casos.etapafluxo')),
            ],
            options={
                'verbose_name': 'Histórico de Etapa',
                'verbose_name_plural': 'Históricos de Etapas',
                'ordering': ['-data_entrada'],
            },
        ),
        migrations.CreateModel(
            name='InstanciaAcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('C', 'Concluída')], default='P', max_length=1)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('descricao_conclusao', models.TextField(blank=True)),
                ('prazo_final', models.DateTimeField(blank=True, null=True, verbose_name='Prazo Final')),
                ('acao_modelo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='casos.acaoetapa', verbose_name='Ação a ser executada')),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acoes_em_andamento', to='casos.caso')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Instância de Ação',
                'verbose_name_plural': 'Instâncias de Ações',
            },
        ),
        migrations.RemoveField(
            model_name='opcaocampo',
            name='nome_label',
        ),
        migrations.RemoveField(
            model_name='opcaocampo',
            name='nome_tecnico',
        ),
    ]
