# Generated by Django 5.2.7 on 2025-10-03 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='caso',
            name='etapa_atual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casos_nesta_etapa', to='casos.etapafluxo'),
        ),
        migrations.CreateModel(
            name='HistoricoEtapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateTimeField(auto_now_add=True)),
                ('data_saida', models.DateTimeField(blank=True, null=True)),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_etapas', to='casos.caso')),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='casos.etapafluxo')),
            ],
            options={
                'verbose_name': 'Histórico de Etapa',
                'verbose_name_plural': 'Históricos de Etapas',
                'ordering': ['-data_entrada'],
            },
        ),
        migrations.CreateModel(
            name='InstanciaAcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('C', 'Concluída')], default='P', max_length=1)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('descricao_conclusao', models.TextField(blank=True)),
                ('acao_modelo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='casos.acaoetapa', verbose_name='Ação a ser executada')),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acoes_em_andamento', to='casos.caso')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Instância de Ação',
                'verbose_name_plural': 'Instâncias de Ações',
            },
        ),
    ]
