# Generated by Django 5.2.7 on 2025-10-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0002_caso_etapa_atual_historicoetapa_instanciaacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='acaoetapa',
            name='prazo_dias',
            field=models.PositiveIntegerField(default=0, help_text='Número de dias para concluir a tarefa após sua criação. 0 para sem prazo.', verbose_name='Prazo (em dias)'),
        ),
        migrations.AddField(
            model_name='acaoetapa',
            name='tipo_prazo',
            field=models.CharField(choices=[('corridos', 'Dias Corridos'), ('uteis', 'Dias Úteis')], default='uteis', max_length=10, verbose_name='Tipo de Prazo'),
        ),
    ]
