# Generated by Django 5.2.7 on 2025-10-05 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0002_acordocaso_despesacaso_parcelaacordo'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelaacordo',
            name='data_quitacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Quitação'),
        ),
    ]
