# Generated by Django 5.2.7 on 2025-10-03 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0003_acaoetapa_prazo_dias_acaoetapa_tipo_prazo'),
    ]

    operations = [
        migrations.AddField(
            model_name='instanciaacao',
            name='prazo_final',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Prazo Final'),
        ),
    ]
