# Generated by Django 5.2.7 on 2025-10-03 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0004_instanciaacao_prazo_final'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='acaoetapa',
            name='responsavel_padrao',
            field=models.ForeignKey(blank=True, help_text='Opcional: O usuário que será o responsável padrão por esta ação.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsável Padrão'),
        ),
    ]
