# Generated by Django 5.2.7 on 2025-10-03 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0005_acaoetapa_responsavel_padrao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acaoetapa',
            name='responsavel_padrao',
        ),
        migrations.AddField(
            model_name='acaoetapa',
            name='responsavel_fixo',
            field=models.ForeignKey(blank=True, help_text="Usado apenas se o tipo acima for 'Usuário Fixo'.", null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário Fixo'),
        ),
        migrations.AddField(
            model_name='acaoetapa',
            name='tipo_responsavel',
            field=models.CharField(choices=[('CRIADOR_ACAO', 'Usuário que Concluiu a Ação Anterior'), ('RESPONSAVEL_CASO', 'Responsável Pelo Caso'), ('USUARIO_FIXO', 'Usuário Fixo (especificar abaixo)')], default='CRIADOR_ACAO', max_length=20, verbose_name='Atribuir Responsável Para'),
        ),
    ]
