# Generated by Django 5.2.7 on 2025-10-03 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0006_remove_acaoetapa_responsavel_padrao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheet',
            name='tempo',
        ),
        migrations.AddField(
            model_name='timesheet',
            name='minutos_gastos',
            field=models.PositiveIntegerField(default=0, verbose_name='Tempo Gasto (em minutos)'),
        ),
        migrations.AlterField(
            model_name='caso',
            name='advogado_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casos_responsavel', to='casos.advogado', verbose_name='Advogado Responsável'),
        ),
    ]
