# Generated by Django 5.2.7 on 2025-10-04 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0007_remove_timesheet_tempo_timesheet_minutos_gastos_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opcaocampo',
            options={'verbose_name': 'Opção de Campo de Lista', 'verbose_name_plural': 'Opções de Campos de Lista'},
        ),
        migrations.AlterUniqueTogether(
            name='opcaocampo',
            unique_together={('campo', 'valor')},
        ),
        migrations.RemoveField(
            model_name='opcaocampo',
            name='nome_label',
        ),
        migrations.RemoveField(
            model_name='opcaocampo',
            name='nome_tecnico',
        ),
    ]
